### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bbjubjub2494** [Groestlcoin/groestlcoin-hash-python#5]
I noticed that this package is treated as non-free by Nixpkgs because it lacks an explicit license. Is this on purpose? A package with a license would be built by NixOS foundation's Hydra along with Electrum for example. Of course you are within your rights to keep it that way.

**Comment by gruve-p** [comment]
> I noticed that this package is treated as non-free by Nixpkgs because it lacks an explicit license. Is this on purpose? A package with a license would be built by NixOS foundation's Hydra along with Electrum for example. Of course you are within your rights to keep it that way.

It wasn't on purpose. We have added a explicit license now: https://github.com/Groestlcoin/groestlcoin-hash-python/commit/2b64ab80da81d48213831775f7f3137542eb6e47
