### ISSUE TITLE
ModuleNotFoundError: No module named 'groestlcoin_hash'

### ISSUE THREAD

**Issue by 10gic** [Groestlcoin/groestlcoin-hash-python#6]
I encountered the error: ModuleNotFoundError: No module named 'groestlcoin_hash'

MacOS Python 3.12.2 virtual environments created with venv. 

Reproduce:
```
$ python --version
Python 3.12.2
$ python -m venv pyvenv
$ . $HOME/pyvenv/bin/activate
$ pip install groestlcoin_hash
Successfully installed groestlcoin_hash-1.0.3
$ python
>>> import groestlcoin_hash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'groestlcoin_hash'
```

**Comment by gruve-p** [comment]
Works fine here on my OSX but without virtual environments (venv)

```
$ python -V
Python 3.6.10
$ pip3 install groestlcoin_hash
Requirement already satisfied: groestlcoin_hash in /usr/local/lib/python3.7/dist-packages (1.0.3)
$ python3
>>> import groestlcoin_hash
>>>
```

**Comment by gruve-p** [comment]
Can you try without the virtual environments? My first guess would be that there is something wrong with your virtual environment.

**Comment by 10gic** [comment]
It's strange. Here are some tests:

MacOS Monterey (12.6):
Python 3.11 without virtual environments: OK
Python 3.11 with virtual environments: OK
Python 3.12 without virtual environments: OK
Python 3.12 with virtual environments: OK

MacOS Sonoma (14.4):
Python 3.11 without virtual environments: OK
Python 3.11 with virtual environments: Fail (ModuleNotFoundError: No module named 'groestlcoin_hash')
Python 3.12 without virtual environments: Not test
Python 3.12 with virtual environments: Fail (ModuleNotFoundError: No module named 'groestlcoin_hash')

**Comment by gruve-p** [comment]
Here are some tests:

MacOS Monterey (12.7.4):
Python 3.7 without virtual environments: OK
Python 3.8 without virtual environments: OK
Python 3.9 without virtual environments: OK
Python 3.10 without virtual environments: OK
Python 3.11 without virtual environments: OK

Ubuntu Jammy (22.04.4 LTS):
Python 3.7 without virtual environments: OK
Python 3.8 without virtual environments: OK
Python 3.9 without virtual environments: OK
Python 3.10 without virtual environments: OK
Python 3.11 without virtual environments: OK

**Comment by gruve-p** [comment]
Maybe the virtual environment on your MacOS Sonoma is corrupt/broken?

**Comment by 10gic** [comment]
Before testing, I recreated the virtual environment.
All right, I'll keep an eye on it.

**Comment by 10gic** [comment]
I suspect that this is caused by the protection software in the computer.
